import 'dart:convert';

import 'package:easthardware_pms/backend/utils/random_int_from_date.dart';
import 'package:easthardware_pms/domain/services/cryptography_service.dart';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;

class SecureHttp {
  const SecureHttp._();

  static Future<http.Response> get(
    Uri uri, {
    Map<String, String>? headers,
  }) async {
    final (sessionKey, encryptionKey, dispose) = await pseudoTlsHandshake(uri);
    try {
      final queryParameters = {"secure-key": "$sessionKey", ...uri.queryParameters};
      final targetUri = uri.replace(queryParameters: queryParameters);

      final response = await http.get(targetUri, headers: headers);

      return http.Response(
        CryptographyService.decryptSymmetric(response.body, encryptionKey),
        response.statusCode,
        headers: response.headers,
        request: response.request,
        isRedirect: response.isRedirect,
        persistentConnection: response.persistentConnection,
        reasonPhrase: response.reasonPhrase,
      );
    } finally {
      await dispose();
    }
  }

  /// Sends a POST request to the specified [uri] with the given [headers] and [body].
  ///   It automatically encrypts the body using a pseudo-TLS handshake. The
  ///   response body is decrypted before returning.
  static Future<http.Response> post(
    Uri uri, {
    Map<String, String>? headers,
    String? body,
  }) async {
    final target = "${uri.host}:${uri.port}";
    if (kDebugMode) {
      print("Target: $target");
    }
    final (sessionKey, encryptionKey, dispose) = await pseudoTlsHandshake(uri);
    try {
      final encryptedBody = body != null //
          ? CryptographyService.encryptSymmetric(body, encryptionKey)
          : null;

      final queryParameters = {"secure-key": "$sessionKey", ...uri.queryParameters};
      final targetUri = uri.replace(queryParameters: queryParameters);
      final response = await http.post(targetUri, headers: headers, body: encryptedBody);

      return http.Response(
        CryptographyService.decryptSymmetric(response.body, encryptionKey),
        response.statusCode,
        headers: response.headers,
        request: response.request,
        isRedirect: response.isRedirect,
        persistentConnection: response.persistentConnection,
        reasonPhrase: response.reasonPhrase,
      );
    } finally {
      await dispose();
    }
  }

  /// Runs a TLS-like handshake with the server at [targetUri] to attempt to
  ///   establish a weakly-secure connection. It basically allows encryption of data
  ///   before being send over HTTP. This does not however, provide any full security.
  /// Basically this allows for weak encryption of data sent over HTTP,
  ///   and should not be used for sensitive data.
  static Future<(int, BigInt, Future<void> Function() closeSession)> pseudoTlsHandshake(
    Uri targetUri, {
    bool isPersistent = false,
  }) async {
    final address = "${targetUri.host}:${targetUri.port}";

    final handshakeRequestUri = Uri.parse(
      'http://$address/handshake-request'
      '?is-persistent=${isPersistent ? 1 : 0}',
    );
    final response1 = await http.get(handshakeRequestUri);
    final handshakeKey = int.parse(response1.body);

    // 1. The 'client hello' message: The client initiates the handshake by sending a "hello" message to the server. The message will include which TLS version the client supports, the cipher suites supported, and a string of random bytes known as the "client random."

    // 2. The 'server hello' message: In reply to the client hello message, the server sends a message containing the server's SSL certificate, the server's chosen cipher suite, and the "server random," another random string of bytes that's generated by the server.
    final clientRandom = BigInt.from(randomIntFromDate());
    final handshakeInitiateUri = Uri.parse(
      "http://$address/handshake-initiate/$handshakeKey"
      "?client-random=$clientRandom",
    );
    final response2 = await http.get(handshakeInitiateUri.replace());
    final decodedResponse2 = jsonDecode(response2.body);

    final BigInt serverRandom;
    final BigInt n;
    final BigInt e;
    // 3. Authentication: The client verifies the server's SSL certificate with the certificate authority that issued it. This confirms that the server is who it says it is, and that the client is interacting with the actual owner of the domain.
    switch (decodedResponse2) {
      case {
          "identity": 1231,
          "serverRandom": final String receivedServerRandom,
          "publicKey": [final String keyN, final String keyE],
        }:
        serverRandom = BigInt.parse(receivedServerRandom);
        n = BigInt.parse(keyN);
        e = BigInt.parse(keyE);
        break;
      case _:
        if (kDebugMode) {
          print('Invalid response $handshakeKey');
        }
        throw Exception('Invalid response');
    }

    // 4. The pre_master secret: The client sends one more random string of bytes, the "pre_master secret." The pre_master secret is encrypted with the public key and can only be decrypted with the private key by the server. (The client gets the public key from the server's SSL certificate.)

    final preMasterSecret = BigInt.from(randomIntFromDate());
    final encrypted = CryptographyService.encryptAsymmetric("$preMasterSecret", n, e);

    // 5. Private key used: The server decrypts the pre_master secret.
    final preMasterUri = Uri.parse(
      "http://$address/handshake-premaster/$handshakeKey"
      "?pre-master=$encrypted",
    );

    // 6. Session keys created: Both client and server generate session keys from the client random, the server random, and the pre_master secret. They should arrive at the same results.
    final encryptionKey = (clientRandom % n) * //
        (serverRandom % n) *
        (preMasterSecret % n);

    final response3 = await http.get(preMasterUri);
    final decrypted = CryptographyService.decryptSymmetric(response3.body, encryptionKey);

    // 7. Client is ready: The client sends a "finished" message that is encrypted with a session key.
    // 8. Server is ready: The server sends a "finished" message encrypted with a session key.
    // 9. Secure symmetric encryption achieved: The handshake is completed, and communication continues using the session keys.
    final confirmationUri = Uri.parse(
      "http://$address/handshake-confirmation/$handshakeKey"
      "?decrypted=$decrypted",
    );
    final response4 = await http.get(confirmationUri);
    if (response4.statusCode != 200) {
      throw Exception('Handshake confirmation failed');
    }

    final sessionKey = int.parse(response4.body);
    Future<void> dispose() async {
      final removeUri = Uri.parse("http://$address/handshake-remove/$handshakeKey");
      await http.delete(removeUri);
    }

    return (sessionKey, encryptionKey, dispose);
  }
}
